[project]
name = "lift-splat-shoot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "efficientnet-pytorch==0.7.0",
    "nuscenes-devkit>=1.2.0",
    "tensorboardx>=2.6.4",
    "torchvision>=0.23.0",
]
